In [1]:
import numpy as np

In [3]:
np.__version__

'1.18.4'

In [15]:
# No. 1
a = np.array
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# No. 2
b = np.zeros((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# No. 3
c = np.full((2,5), 5)
print(c)

[[5 5 5 5 5]
 [5 5 5 5 5]]


In [26]:
my_array = np.zeros((5,3))
for i in my_array:
    print(i+2)

[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
