In [2]:
import numpy as np

# 2D

In [3]:
base_1 = np.random.randint(10, size = (5, 5))
print(base_1)

[[5 3 7 5 5]
 [5 6 4 7 8]
 [3 4 2 6 3]
 [9 8 6 3 9]
 [5 3 3 6 3]]


In [4]:
print(base_1[2, 2]) # row, column

2


In [5]:
print(base_1[2, 2:5])

[2 6 3]


# 3D

In [6]:
base_2 = np.random.randint(10, size = (3, 5, 5))
print(base_2)

[[[8 3 3 2 4]
  [4 4 0 9 7]
  [0 4 3 7 8]
  [0 9 6 7 7]
  [2 1 2 7 9]]

 [[1 3 1 0 7]
  [4 3 5 7 3]
  [1 6 8 2 2]
  [7 0 8 5 5]
  [7 7 8 2 2]]

 [[0 8 5 4 0]
  [0 3 0 5 8]
  [0 3 0 9 8]
  [4 1 9 0 6]
  [4 9 9 1 8]]]


In [7]:
print(base_2[0, 1, 3]) # grup besar, row, column

9


In [8]:
print(base_2[:, [0, 2]])

[[[8 3 3 2 4]
  [0 4 3 7 8]]

 [[1 3 1 0 7]
  [1 6 8 2 2]]

 [[0 8 5 4 0]
  [0 3 0 9 8]]]


# Soal

## Specifics

In [9]:
soal_a = np.random.randint(10, size = (5, 5))
print(soal_a)
print(soal_a[2, 0])

[[5 8 4 4 3]
 [7 8 6 8 9]
 [5 3 2 8 2]
 [1 6 1 9 5]
 [6 1 5 5 5]]
5


In [10]:
soal_b = np.random.randint(10, size = (5, 5))
print(soal_b)
print(soal_b[2, 0:3])
print(soal_b[2, 2:5])

[[1 6 4 9 9]
 [1 3 4 0 7]
 [8 5 2 8 7]
 [8 4 2 2 4]
 [9 8 1 0 9]]
[8 5 2]
[2 8 7]


In [11]:
soal_c = np.random.randint(10, size = (2, 5, 5))
print(soal_c, "\n")
print(soal_c[:, 1, 0:3],"\n", soal_c[:, 1, 2:5])

[[[2 9 8 3 7]
  [2 1 3 8 0]
  [6 8 0 6 4]
  [3 9 0 5 3]
  [1 2 4 4 3]]

 [[5 3 5 2 9]
  [9 3 0 7 9]
  [7 5 4 4 0]
  [3 6 2 5 9]
  [0 6 2 6 0]]] 

[[2 1 3]
 [9 3 0]] 
 [[3 8 0]
 [0 7 9]]


In [12]:
soal_d = np.array([[1, 1, 1, 1, 1],
                  [1, 2, 2, 2, 1],
                  [1, 2, 3, 2, 1],
                  [1, 2, 2, 2, 1],
                  [1, 1, 1, 1, 1]])
print(soal_d)

one = np.ones((5, 5), dtype = 'int32')
two = np.full((3, 3), 2, dtype = 'int32')
two[1, 1] = 3
one[1:-1, 1:-1] = two
print(one)

[[1 1 1 1 1]
 [1 2 2 2 1]
 [1 2 3 2 1]
 [1 2 2 2 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 2 2 2 1]
 [1 2 3 2 1]
 [1 2 2 2 1]
 [1 1 1 1 1]]


In [13]:
one[0:5, 2] = 3
print(one)

[[1 1 3 1 1]
 [1 2 3 2 1]
 [1 2 3 2 1]
 [1 2 3 2 1]
 [1 1 3 1 1]]
