# Load in NumPy

In [1]:
import numpy as np
import sys

# The Basics

In [2]:
a = np.array([1, 2, 3], dtype='int8')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
print("Dimension", a.ndim, b.ndim)

Dimension 1 2


In [5]:
# Get Shape
print("Shape", a.shape, b.shape)

Shape (3,) (2, 3)


In [6]:
# Get Type
print("Type", a.dtype, b.dtype)

Type int8 float64


In [7]:
# Get Size
print("Size", a.itemsize, b.itemsize)
print("Size", a.size, b.size)

Size 1 8
Size 3 6


In [8]:
# Get total size
print("Total Size", a.nbytes, b.nbytes)

Total Size 3 48


# Accessing/Changing specific elements, rows, columns, etc

In [9]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element [row, column]
a[1,5]

13

In [11]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [13]:
# Getting a little more fancy [startindex: endindex: stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [14]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3D Example

In [15]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [17]:
# Replace
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [18]:
# All 0s matrix
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [19]:
# All 1s matrix
np.ones((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [20]:
# Any other number
np.full((2,2), 93)

array([[93, 93],
       [93, 93]])

In [21]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.10903788, 0.59888532],
       [0.85509291, 0.52780586],
       [0.34795508, 0.92624567],
       [0.71895207, 0.38837672]])

In [23]:
# Random decimal number as much shape
np.random.random_sample(a.shape)

array([[0.43528498, 0.15753129, 0.22022895, 0.24771113, 0.39499517,
        0.57025597, 0.06846258],
       [0.64353943, 0.09472546, 0.20423963, 0.21765235, 0.92391163,
        0.77845057, 0.23403367]])

In [24]:
# Random Integer Values
np.random.randint(7, size = (3, 3))

array([[5, 4, 6],
       [4, 3, 2],
       [4, 3, 1]])

In [25]:
# The identity matrix
np.identity(5, dtype = 'int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [27]:
output = np.ones((5, 5), dtype = 'int32')
print(output)

z = np.zeros((3, 3), dtype = 'int32')
z[1, 1] = 9

print(z)

output[1:-1, 1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be careful when copying arrays!!!

In [28]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [29]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [30]:
a + 2

array([3, 4, 5, 6])

In [31]:
a - 2

array([-1,  0,  1,  2])

In [32]:
a * 2

array([2, 4, 6, 8])

In [33]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [34]:
a // 2

array([0, 1, 1, 2], dtype=int32)

In [35]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [36]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [37]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algebra

In [38]:
a = np.ones((2, 3), dtype = 'int32')
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [39]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

### Determinant
### Trace
### Singular Vector Decomposition
### Eigenvalues
### Matrix Norm
### Inverse
### Etc...

# Statistics

In [40]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [42]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [43]:
np.sum(stats, axis = 0)

array([5, 7, 9])

# Reorganizing Arrays

In [44]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape(2, 2, 2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# Horizontally stacking vectors
h1 = np.ones((2, 4), dtype = 'int32')
h2 = np.zeros((2, 2), dtype = 'int32')

np.hstack([h1, h2])

array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0]])

# Miscellaneous

## Load Data from File

In [51]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## Boolean Masking and Advanced Indexing

In [53]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [54]:
## You can index with a list in NumPy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [55]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [56]:
(filedata > 50) & (filedata < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [57]:
~(filedata > 50) & (filedata < 100)

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

# Exercise

In [78]:
a = np.arange(1, 31, 1).reshape(6, 5)
print(a)
b = a[2:4, 0:2]
c = a[[0, 1, 2, 3], [1, 2, 3, 4]]
d = a[[0, 4, 5], 3:]
print(b)
print(c)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
